### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by oliversalzburg**
This is primarily intended to fix the security issue with useragent.

### CODE REVIEW

**Comment by kslonka** [comment]
Can someone merge it?

**Comment by neeharv** [comment]
Just checking in - is this good to be merged in and released?

**Comment by oliversalzburg** [comment]
No objection from my end :)

**Comment by oleg-koval** [comment]
Hi guys, can somebody merge this one please:)?

**Comment by tonyxiao** [comment]
Is there a fork we could use in the meantime?

**Comment by tonyxiao** [comment]
whoa that was blazing fast. Thanks @marcbachmann !!

**Comment by marcbachmann** [comment]
Released as `express-bunyan-logger@1.3.3`

**Comment by marcbachmann** [comment]
Yeah, I just finished watching agents of shield, opened github and saw that message. 
Have a good weekend.

**Comment by oliversalzburg** [comment]
@marcbachmann I don't think I could have merged this. Thanks for taking care of it :)

**Pull request merged**
