### PR TITLE
Test against more recent Node versions

### PR DESCRIPTION
**Pull request by oliversalzburg**

### CODE REVIEW

**Comment by oliversalzburg** [comment]
@marcbachmann Are you a maintainer of this project? We opened #47 a while ago and there has been no activity since. We're considering a fork.

**Comment by marcbachmann** [comment]
I have permission to merge and publish but I'm not really using this module anymore.

**Comment by oliversalzburg** [comment]
We recently included it into our web stack and would appreciate if changes were merged upstream to avoid further fragmentation.

**Comment by marcbachmann** [comment]
I'm using http://npm.im/pino everywhere. You might want to switch to that as it's pretty well maintained and backed by nearform. The api is quite similar to bunyan and also this module.

**Comment by oliversalzburg** [comment]
Thanks for the heads-up :D But our move to bunyan isn't even that far in the past and we're still building up our code around it. Moving to something new right now would probably not fit our budget.

**Comment by lutangar** [comment]
Hey @villadora, it seems like @marcbachmann can't maintain `express-bunyan-logger` anymore, maybe you could get in touch with @oliversalzburg or just add him as a maintainer, since their team is still using this project on a daily basis.

**Comment by marcbachmann** [comment]
Looks like by now I had permission to add @oliversalzburg to the npm repo.

**Comment by marcbachmann** [comment]
I'd say we should setup semantic release, so releasing something is much easier.

**Comment by oliversalzburg** [comment]
We would be happy to maintain it. I'll wait for @villadora to give us a signal :)

**Pull request merged**
